POST http://localhost:3001/auth/register
content-Type: application/json

{
    "username": "testuser",
     "password": "123456"
}

###
POST http://localhost:3001/auth/login
content-Type: application/json

{
    "username": "testuser",
     "password": "123456"
}

###
//get thong tin gio hang tren db
GET http://localhost:3001/cart/infocart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjEsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE2NTc0NDIxMDUsImV4cCI6MTY1Nzc0MjEwNX0.Vy4CWZ8rCwVHojK58G0QnuDeDHtkc--c75AAcwwKJuI
###
POST http://localhost:3001/cart/producttocart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzZXIiOjEsInVzZXJuYW1lIjoidGVzdHVzZXIiLCJpYXQiOjE2NTc0NDIxMDUsImV4cCI6MTY1Nzc0MjEwNX0.Vy4CWZ8rCwVHojK58G0QnuDeDHtkc--c75AAcwwKJuI
Content-Type: application/json

 {
    
    "idproduct": "ribs-brisket-and-burnt-ends",
    "img": "https://goldbelly.imgix.net/uploads/showcase_media_asset/image/79619/joes-kc-ribs-brisket-and-burnt-ends.6710e994980e485e6441b794717ad6fb.jpg?ixlib=react-9.0.2&auto=format&ar=1%3A1",
    "name": "Joe's KC BBQ",
    "dsc": "Joe's KC Ribs, Brisket & Burnt Ends",
    "price": "110.99",
    "rate": "4",
    "country": "Kansas City, KS",
    "quatityproduct": 1
  }